/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaToC_DirectFourierTransform */

#ifndef _Included_javaToC_DirectFourierTransform
#define _Included_javaToC_DirectFourierTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaToC_DirectFourierTransform
 * Method:    direct
 * Signature: ([DIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_javaToC_DirectFourierTransform_direct
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
